### ISSUE TITLE
Travellers Compass is adding empty NBT tags to any item held

### ISSUE THREAD

**Issue by GeekyBakerBen** [0Templ/TravelersCompass#1]
Travellers Compass v1.0.0 on Fabric 1.20.1

When the compass is in my inventory, any item I hold for more than a couple of seconds gets an empty NBT tag added to it, thus making it unstackable with any existing items of the same type.

I know it's the compass doing it as the problem goes away the second I take the compass out of my inventory, and comes back as soon as I put it back in.

I do believe the compass may have been actively searching in the background at the time (for anything, be it block or entity). Only affects the item (or stack of items) I hold in my hand for a few seconds - it's also indicated by a slight "flinch" of the item as it updates, as though I've just picked it up anew.

**Comment by 0Templ** [comment]
Fixed in version 1.0.10 (Fabric)
