### ISSUE TITLE
Severe crash issue causing the world to fail to load and become inaccessible, and compass can't change target before crash.

### ISSUE THREAD

**Issue by NotShaung** [0Templ/TravelersCompass#10]
Currenty have an issue that compass bug can make you can't load you world unless you remove the mod.

Before the crash occurred, my compass couldn't switch its search target and was stuck on the previous one (the previous item it was searching for was inside a chest). After I pressed the reset button in the settings, the crash happened, and I couldn't re-enter the world file until I temporarily removed the mod.

Here's log:
https://gist.github.com/NotShaung/a1bdf23757f1196a332bfc0cf4f89820

**Comment by 0Templ** [comment]
Thanks for pointing out this issue!
Fixed in [3.1.03](https://legacy.curseforge.com/minecraft/mc-mods/travelers-compass/files/5952943).
To make the compass actively switch search targets, you need to turn off 'Lazy-search' mode in the compass menu.
