### ISSUE TITLE
Crash when breaking selected block in compass

### ISSUE THREAD

**Issue by Gaz492** [0Templ/TravelersCompass#11]
If you go to the block selected in the compass, the game will crash as it tries to divide by 0.
crashlog https://pste.ch/arinakuqop.coffeescript

Steps to reproduce

1. select a block (e.g. Budding amethyst)
2. follow the compass
3. break the block
4. crash and unable to rejoin

Issue was originally reported at: https://github.com/FTBTeam/FTB-Modpack-Issues/issues/6484

**Comment by 0Templ** [comment]
Thanks
Should be fixed in [3.1.04](https://www.curseforge.com/minecraft/mc-mods/travelers-compass/files/6019676).

**Comment by SuperKnux** [comment]
could you please backport the fix to 1.20.1? a friend of mine has encountered the divide by zero ticking bug on my server.

**Comment by 0Templ** [comment]
> could you please backport the fix to 1.20.1? a friend of mine has encountered the divide by zero ticking bug on my server.

Sorry for the late reply. Fix released

**Comment by phit** [comment]
where is the source code for those newer versions? can one safely upgrade to 3.1.04 from 3.1.03 on the server only?

**Comment by 0Templ** [comment]
> where is the source code for those newer versions? can one safely upgrade to 3.1.04 from 3.1.03 on the server only?

I haven't uploaded the code to gitHub yet.
Both server and client versions should be updated.
