### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Apiterbakar** [0Templ/TravelersCompass#3]
[crash-2024-07-11_16.40.45-fml.txt](https://github.com/user-attachments/files/16179553/crash-2024-07-11_16.40.45-fml.txt)

**Comment by 0Templ** [comment]
Hello! 
I haven't been able to replicate this issue on this version of forge. Probably there is a conflict with some other mod...

If you are using a public mod-pack, send me a link to it so I can understand where exactly the issue is.

**Comment by Apiterbakar** [comment]
umm i don't use public modpack but here is the log so you can see my modlist
[2024-07-11-3.log.gz](https://github.com/user-attachments/files/16185343/2024-07-11-3.log.gz)
