### ISSUE TITLE
Crash when used

### ISSUE THREAD

**Issue by KevzCz** [0Templ/TravelersCompass#4]
https://mclo.gs/rYzm715. This is a crash report on a modded server (FantasyMC Fabric modpack)
We thought it was an issue with how big its search radius was but it wasnt that

**Comment by 0Templ** [comment]
This issue was fixed in version [3.0.4](https://www.curseforge.com/minecraft/mc-mods/travelers-compass/files/5479299). You need to update this mod on both the server and the client to avoid this error.
