### ISSUE TITLE
crash on dedicated server

### ISSUE THREAD

**Issue by EthanDangerous** [0Templ/TravelersCompass#5]
my friend got this bug and crashed when they searched for something (and when they searched for nothing)

[09:51:26] [Netty Epoll Server IO #3/ERROR] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER

is there a fix for this?

**Comment by EthanDangerous** [comment]
this does not work in singleplayer though
or in creative
this is the link for the pack: https://www.dropbox.com/scl/fi/qqzjjueoj7x6uhtzfzpde/SWMG-pack.zip?rlkey=fi0jspkmgg6v3aind5wjw1uom&st=yzxgmq17&dl=0

**Comment by 0Templ** [comment]
Hello! 
Are you sure you are using one of the latest versions of the mod (3.0.4 and older)?  I can't find Traveler's Compass [here](https://www.dropbox.com/scl/fi/qqzjjueoj7x6uhtzfzpde/SWMG-pack.zip?rlkey=fi0jspkmgg6v3aind5wjw1uom&st=yzxgmq17&dl=0)

> this does not work in singleplayer though or in creative this is the link for the pack: https://www.dropbox.com/scl/fi/qqzjjueoj7x6uhtzfzpde/SWMG-pack.zip?rlkey=fi0jspkmgg6v3aind5wjw1uom&st=yzxgmq17&dl=0
