### ISSUE TITLE
Server lag with high player count

### ISSUE THREAD

**Issue by SuperKnux** [0Templ/TravelersCompass#6]
Minecraft Version: 1.20.1
Traveler'sCompass Version: 3.0.4

![image](https://github.com/user-attachments/assets/201064f8-13cb-4b40-9630-ba09a8bb2090)

The server receives heavy TPS lag relating to the compass mod, relating to the image I posted.

**Comment by 0Templ** [comment]
Since the compass scans every block around, having a large search radius can cause lag, especially when multiple players are using it. You can limit the search radius for containers and blocks in the config file (Searching for entities shouldn't cause lags.) 
That should help with the lags.

**Comment by SuperKnux** [comment]
Noting that this is without anyone even having the compass yet.
Why is the mod doing all this calculation when the mod's compass isn't even being used right now?

**Comment by 0Templ** [comment]
> Noting that this is without anyone even having the compass yet. Why is the mod doing all this calculation when the mod's compass isn't even being used right now?

The compass only performs calculations if it is in the player's inventory, is not paused, is not empty, and at least one search mode is selected.
Otherwise it should not work
