### ISSUE TITLE
can not see compass

### ISSUE THREAD

**Issue by Aikus1** [0Templ/TravelersCompass#7]
Hi I am someone new to modded Minecraft. I was using Vshojo craft mod pack and  I noticed was unable to use the recipe to make the compass, along with a couple other items too. I am unsure of what to do to fix this as it uses both JEI and EMI mod.
 **game launcher prism**.
**minecraft version 17.
mod version 2.0.4.0**.

**Comment by 0Templ** [comment]
Hello!
I apologize for such a slow response.
If the issue is still present when using the latest version of the mod, please specify what the problem is.
