### ISSUE TITLE
[1.21] [Fabric] [Singleplayer] lag: slight delay after every few seconds

### ISSUE THREAD

**Issue by cL1cKyB** [0Templ/TravelersCompass#8]
after I used the mod without any issues for my world for 2 weeks, recently when the compass was enabled, a multiplayer-like lag appeared where the game freezes/delays a slight seconds after a few seconds(approx. 3sec interval). 

Short video where swapping items stutters and the zombie freezes a few times. 
https://github.com/user-attachments/assets/318d03c3-2168-472d-9228-1babf25729fd

list of the used mods
[mod_list.txt](https://github.com/user-attachments/files/16444007/mod_list.txt)

I also disabled Distant Horizon for the video.

If any logs are required, I will provide them

**Comment by 0Templ** [comment]
#6 
Since the compass scans every block around, having a large search radius can cause lags.
Reduce the search radius of blocks and containers.
